### PR TITLE
fix: add safe stringify to format winston events

### PR DESCRIPTION
**Pull request by lucassmuller**
**Issue:** Current `JSON.stringify` doesn't support bigints. This results in logs not being sent to Axiom.

**Solution:** Implement `toJSON` function in BigInt prototype so they can be stringified.

### CODE REVIEW

**Comment by schehata** [comment]
I updated the pnpm lock file on main, can you please rebase this PR, I will approve the CI again once its ready.

**Comment by lucassmuller** [comment]
> I updated the pnpm lock file on main, can you please rebase this PR, I will approve the CI again once its ready.

done

btw the root cause of this problem is actually the following code line

https://github.com/axiomhq/axiom-js/blob/70c846719f3b4fd2e05475787f368af5189f476b/packages/js/src/client.ts#L163

probably i should adjust it there. thoughts?

**Comment by schehata** [comment]
> > I updated the pnpm lock file on main, can you please rebase this PR, I will approve the CI again once its ready.
> 
> done
> 
> btw the root cause of this problem is actually the following code line
> 
> https://github.com/axiomhq/axiom-js/blob/70c846719f3b4fd2e05475787f368af5189f476b/packages/js/src/client.ts#L163
> 
> probably i should adjust it there. thoughts?

yeah, here it would with other transports as well, not just winston. go for it 👍

Do you have a test case that we can apply here?

**Comment by lucassmuller** [comment]
> > > I updated the pnpm lock file on main, can you please rebase this PR, I will approve the CI again once its ready.
> > 
> > 
> > done
> > btw the root cause of this problem is actually the following code line
> > https://github.com/axiomhq/axiom-js/blob/70c846719f3b4fd2e05475787f368af5189f476b/packages/js/src/client.ts#L163
> > 
> > probably i should adjust it there. thoughts?
> 
> yeah, here it would with other transports as well, not just winston. go for it 👍
> 
> Do you have a test case that we can apply here?

Done

**Pull request merged**
